ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
  SUCCESS_THRESH: 5
SIMULATOR:
  CTRL_HZ: 30
  SIM_HZ: 30
  SETTLE_TIME: 20
  FLOOR_SEPARATION: 20.0
DEBUG:
  FIXED_BASE: False
  BASELINE_POLICY: False

ROBOT:
  ROBOT_URDF: data/URDF_demo_assets/aliengo/urdf/aliengo.urdf
  START:
    CALF: -2.5
    THIGH: 1.3
  STANDING_POSE: [ 0.0, 0.698132, -1.39626 ]  # Hip, shoulder, knee
  JOINT_LIMITS: # Hip, shoulder, knee
    LOWER: [ -0.1, -1.047, -2.62 ]
    UPPER: [ 0.1, 1.496, -0.785 ]
  JOINT_LIMITS_STAND: [ 0.15, 0.4, 0.4 ] # Relative to the stand pose
  ROBOT_SPAWN_HEIGHT: 0.6

TASK:
  ACTION:
    NUM_JOINTS: 12
    MAX_DEGREE_DELTA: 10 # in degrees
    TYPE: relative
  JITTER_THRESHOLD: 0.0349066  # 2 degrees (in radians)
  REWARD:
    TIP_PENALTY: 1
DATASET:
  TYPE: ""
  CONTENT_SCENES: []
